version: "3.9"  # optional since v1.27.0
services:
  my-app:
    build: .
    environment:
        ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8090:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: oisehrdugfols32k4l3r.ewrtkp25t43-0e9r4r3er